### ISSUE TITLE
POST processing request to server

### ISSUE THREAD

**Issue by Yuhan-Liu-Heidi** [NicolasHu11/BME547Final#19]

**Comment by Yuhan-Liu-Heidi** [comment]
@chriszhou0916  Could you please tell me the keys of the dictionary you need to process images?

**Comment by chriszhou0916** [comment]
I check for these fields
https://github.com/NicolasHu11/BME547Final/blob/3887a6cc32a953ed8a242faa96fecdfe2a5c3ae0/server.py#L143-L149
imgs and filename are lists

**Comment by chriszhou0916** [comment]
Feature implemented
