### ISSUE TITLE
Query user information for user that does not exist

### ISSUE THREAD

**Issue by chriszhou0916** [NicolasHu11/BME547Final#24]
Hey Nick, I found a potential bug in the code.

The code works if I query for the request_ids of a username that exists. The server is crashing if the user doesn't exist. We need to send the GUI a specific message if the user doesn't exist. I am using this command to get the list of requests:

`request_id = query_field(username, 'request_id')`

Can you add something in your db file to tell me if the user doesn't exist? You can return 0 instead of a list of request_ids

**Comment by chriszhou0916** [comment]
A similar issue: what happens if I query for a request_id that doesn't exist?

**Comment by NicolasHu11** [comment]
Hi Chris, 
I have update the functions in branch  `N/DB_query_bug_fix` : 

`query_field(username, field)`:  return 0 if user does not exist. 
`update_field(username, field, value)`:  return 0 if user does not exist. 
`query_by_request_id(username, request_id)`:  return 0 if user does not exist. return 1 if request id does not exist.

the code you used, `request_id = query_field(username, 'request_id')`, is to query a field, which is intended to return the list of request ids( could be an empty list if there is no request been made). If you want to get the lastest request id, add [-1] in the end. 

You could use `query_by_request_id(username, request_id)` if you want to query ONE specific request.

**Comment by chriszhou0916** [comment]
Thank you. I included it in my server code too.

Followup question:
When would update_field() be used? Is it a helper function you wrote for yourself?

**Comment by NicolasHu11** [comment]
Yes, it's for me. It's used to update one field with a new value. You don't have to use it.
