### ISSUE TITLE
Communicating using issues and comments

### ISSUE THREAD

**Issue by dward2** [NicolasHu11/BME547Final#30]
@chriszhou0916 @Yuhan-Liu-Heidi @NicolasHu11 It looks like you are making some progress on your project.  You have made good use of the issues and assigning them to milestones and individual team members.  One thing we will also be looking for is intra-team communication, specifically how you use comments in the issues to communicate as a team.  As you are working together over the next few days, consider how you might use comments in issues as a way of doing some of your communication.

**Comment by chriszhou0916** [comment]
Thanks Dr. Ward for your comments. We will definitely make use of issue comments more this week.
