### ISSUE TITLE
database functions update

### ISSUE THREAD

**Issue by NicolasHu11** [NicolasHu11/BME547Final#34]
Hey @chriszhou0916,

1. I just added more database functions  as we discussed earlier and merged it into the master branch. 
- query_user_metrics(username):
- query_request_metadata(username,request_id):
- check_user(username):

2. Also, I add `user_creation_time` in the user and update the `create_new_user` function accordingly.

3. Also, I update the `num_actions` into dictionary type in user, and update it in `save_a_new_request` function.

**Comment by chriszhou0916** [comment]
Thanks Nick. I will update my code to support these functions
